alter table PLANNERTEST_SESSION add constraint FK_PLANNERTEST_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PLANNERTEST_SPEAKER(ID);
create index IDX_PLANNERTEST_SESSION_ON_SPEAKER on PLANNERTEST_SESSION (SPEAKER_ID);
