-- begin PLANNERTEST_SESSION
alter table PLANNERTEST_SESSION add constraint FK_PLANNERTEST_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PLANNERTEST_SPEAKER(ID)^
create index IDX_PLANNERTEST_SESSION_ON_SPEAKER on PLANNERTEST_SESSION (SPEAKER_ID)^
-- end PLANNERTEST_SESSION
-- begin PLANNERTEST_SPEAKER
create unique index IDX_PLANNERTEST_SPEAKER_UNIQ_EMAIL on PLANNERTEST_SPEAKER (EMAIL)^
create index IDX_PLANNERTEST_SPEAKER_LAST_NAME on PLANNERTEST_SPEAKER (LAST_NAME)^
-- end PLANNERTEST_SPEAKER
